### ISSUE TITLE
大兄dei，提交的d里有个fc字段不需要写吗？

### ISSUE THREAD

**Issue by saberrey** [icefiresS/Mikecrm-BOT#1]
好像还有个fc字段在提交的d里，我看了js源码看不懂它咋来的

**Comment by ErthoAers** [comment]
emmmm之前大概是不需要的，但是后来听几个同学说用不了，那大概是mikecrm改了接口吧。。我也懒得维护了23333

**Comment by ErthoAers** [comment]
你可以抓一下POST的包看看这个字段填了什么

**Comment by saberrey** [comment]
> 你可以抓一下POST的包看看这个字段填了什么

其实我之前也写了一个能用，后来发现他多了一个fc，看了半天也不知道怎么来的，不太会JavaScript :( ，我再研究研究吧
